# Panda

it is the basic libraray used in python in order to work the data sheet.
It has functions for analyzing, cleaning, exploring, and manipulating data.

In [19]:
#import of pandas to used its inbuilt function in our code.
import pandas as pd

# Series
it is like a column of table. it holds the data  of any type. it is also called 1-d arrays.

In [32]:
#series
import pandas as pd
a=[1,2,3,4]
series= pd.Series(a)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
import pandas as pd
a=["A","B","C"]
s=pd.Series(a,index=["a","b","c"])
print(s)

a    A
b    B
c    C
dtype: str

In [24]:
# key/value concept
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390} # the key of dictionary becomes the label

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [103]:
import pandas as pd
dic={
    "name":"ishan",
    "class":12
}
b=pd.Series(dic,index=["name"])
print(b)

name    ishan
dtype: object

# DataFrame
Series is like a column, a DataFrame is the whole table. it contains rown and columns.(2-dimension)

In [104]:


import pandas as pd
dic={
   "name":["ishan","ram","sita"],
   "age":[11,12,23],
   "class":[12,15,13]
}
d=pd.DataFrame(dic)
print(d)

    name  age  class
0  ishan   11     12
1    ram   12     15
2   sita   23     13

In [105]:

# indexing  or labeling according to our choice
import pandas as pd
dic={
   "name":["ishan","ram","sita"],
   "age":[11,12,23],
   "class":[12,15,13]
}
d=pd.DataFrame(dic,index=["1","2","3"])
print(d)

    name  age  class
1  ishan   11     12
2    ram   12     15
3   sita   23     13

For acessing specific data we use loc sytnax.

In [61]:
import pandas as pd
dic={
    "name":["ishan","ram","sita"],
       "age":[11,12,23],
       "class":[12,15,13]
    
}
d=pd.DataFrame(dic,index=[1,2,3])
print(d.loc[1])# only printing the index 1
print("------------------------------")
print(d.loc[[1,3]])# printing the value of index 1 and 3

name     ishan
age         11
class       12
Name: 1, dtype: object
------------------------------
    name  age  class
1  ishan   11     12
3   sita   23     13

# Load file in DataFrame

If your data sets are stored in a file, Pandas can load them into a DataFrame.

MEANS:

Instead pf wrotomg data in dictionary form the use dataframe to convert into tabular form we can directly write the data in coma form in .csv file extension the use it to convert into tabular form.

Eaxample:

Name,age,class

ishan,22,12

ram,12,4
  
and so on like this

In [102]:
#reading the data for csv form
import pandas as pd
d=pd.read_csv('data.csv')#data asre already stored in data.csv in comma form 
print(d)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135       NaN
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

# Pandas read csv

In [101]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string()) # here df.to_string() print whole data into plain text form i.e. string form

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135       NaN
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

# Viewing the Data

In [100]:
import pandas as pd
a=pd.read_csv('data.csv')
print(a.head(2))# here head(2) means show top  two rows only
print("--------------------------------------------")
print(a.tail(2)) # it means buttom two tows only
print("--------------------------------------------")
print(a.head())# it will read first 5 rows

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
--------------------------------------------
    Duration  Pulse  Maxpulse  Calories
18        60    103       123     323.0
19        45     97       125     243.0
--------------------------------------------
   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135       NaN
3        45    109       175     282.4
4        45    117       148     406.0

In [99]:
# table info
import pandas as pd
a=pd.read_csv("data.csv")
print(a.info())#gives you more information about the data set.

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  20 non-null     int64
 1   Pulse     20 non-null     int64
 2   Maxpulse  20 non-null     int64
 3   Calories  18 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 772.0 bytes
None

# Cleaning Data

cleaining data means fixing the bad data of datasheet.like wrong format of data, duplicate, empty one etc.

In [98]:
# cleaning empty cells
# removing that empty cell row 
import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.head(10).to_string()) #below output terminal we can index 2 row is remove as it contains missing value

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3

In [97]:
# replacing null value
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(132, inplace = True)# inplace=true means tell pandas to modify the original data directly

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     132.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112     132.0
18        60    103       123     323.0
19        45     97       125     243.0

in above it replace all the empty one with assign value and now assigning the value to specific one

In [96]:
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna({"Calories": 130}, inplace=True)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     130.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112     130.0
18        60    103       123     323.0
19        45     97       125     243.0

 # filtering

it means acessing the data only the one we want which is called filtering. for example we want students name for datasheet of only those students who read in class 4 then we can us filtering properties and obtain only that one.

In [108]:
#assigning only the one pulse data
import pandas as pd
df=pd.read_csv("data.csv")
df1=df["Pulse"]
print(df1.head(10).to_string())

0    110
1    117
2    103
3    109
4    117
5    102
6    110
7    104
8    109
9     98

In [121]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df[df["Duration"] ==45].to_string())

    Duration  Pulse  Maxpulse  Calories
3         45    109       175     282.4
4         45    117       148     406.0
7         45    104       134     253.3
17        45     90       112       NaN
19        45     97       125     243.0

#  sorting

sorting means arranging the value in ascending or desceding order based on their column value

In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
df1=df.sort_values("Pulse",ascending=False).head(5)# arranged in descending order
print(df1)

   Duration  Pulse  Maxpulse  Calories
1        60    117       145     479.0
4        45    117       148     406.0
6        60    110       136     374.0
0        60    110       130     409.1
8        30    109       133     195.1

# Indexing

Indexing is one of the most important concepts in Pandas. It is how Pandas identifies, selects, and accesses rows and columns in a DataFrame or Series.

If we understand indexing well, we will be able to filter, modify, and analyze data easily.

There are mainly four ways to index data.

1)Column indexing

2)Row indexing

3)loc[]

4)iloc[]

In [8]:
#1 column indexing
import pandas as pd
df=pd.read_csv("data.csv")
print(df["Pulse"].head(10))# print plne one column
print("--------------------------------------")
print(df[["Pulse","Duration"]].head(10))# print multiple column

0    110
1    117
2    103
3    109
4    117
5    102
6    110
7    104
8    109
9     98
Name: Pulse, dtype: int64
--------------------------------------
   Pulse  Duration
0    110        60
1    117        60
2    103        60
3    109        45
4    117        45
5    102        60
6    110        60
7    104        45
8    109        30
9     98        60

# Row Indexing 
using slicing

In [11]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df[0:5])

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135       NaN
3        45    109       175     282.4
4        45    117       148     406.0

 # Using .loc[] (Label-Based Indexing)

.loc[] selects rows and columns by their labels (index names and column names).

In [16]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.loc[2]) # get 2nd row

Duration     60.0
Pulse       103.0
Maxpulse    135.0
Calories      NaN
Name: 2, dtype: float64

In [17]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.loc[2:7])

   Duration  Pulse  Maxpulse  Calories
2        60    103       135       NaN
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3

 # .iloc[] (Position-Based Indexing)

iloc=integer location

This means it accesses data using integer positions (0, 1, 2, 3, ...), not row labels or column names.

In [18]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.iloc[2:7])

   Duration  Pulse  Maxpulse  Calories
2        60    103       135       NaN
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0